### ISSUE TITLE
fml-asm: mrope.c:230: mr_insert_multi: Assertion `len > 0 && s[len-1] == 0' failed.

### ISSUE THREAD

**Issue by davisem** [lh3/fermi-lite#12]
This exception is thrown when short sequences are encountered.

```
@0:1    4281    .    .
CCCACAGAACTAAAACAGAAGAATTCTC
@0:2    4281    .    .
CCTAGACAGAACCCATCTAAGAAACGAC
```

I have seen this on occasion when a read is truncated.

Thanks.

**Comment by lh3** [comment]
Let me know if the problem persists. Thanks!
