### ISSUE TITLE
Possible Error in bfc_ec1dir?

### ISSUE THREAD

**Issue by MartinDrab** [lh3/fermi-lite#6]
Hello,

I am using the error correction code of fermi-lite in my thesis and it works pretty well. I have noticed that count k-mer occurrences with help of a table built on top of a set of khash tables (enhanced with locking support). The lowest 14 bits of table keys is used to count occurrences of corresponding k-mers. Bits 0-7 count low quality instances, 8-13 are responsible for high-quality ones.

So, to extract the low-quality occurence, you need just to AND the key with the 0xff mask. To get the high-quality one, a right shift of 8, followed by AND with 0x3f mask, is required. 

On line 450 of the bfc.c file (the bfc_ec1dir function), there is probably a wrong mask applied:
`pen.absent_high = ((s>>8&0xff) < e->opt->min_cov);`

Can you look into it please? I think I have quite deep understanding of the code now but I am still probably missing few details..

**Comment by MartinDrab** [comment]
Also, line 458 of the same file seems to be subject to the same problem.

**Comment by lh3** [comment]
Thanks.

See function `bfc_ch_get()` in `htab.c`. The returned value has been masked with `0x3fff` (`htab.c:91`). `s` at `bfc.c:450` only has 14 bits. Mask `0xff` gives the desired result.
